### PR TITLE
Wri 445  submenu links

### PR DESCRIPTION
**Pull request by komejo**
## What issue(s) does this solve?

- [x] Issue Number: [#445](https://github.com/wri/WRIN/issues/445)

## What is the new behavior?
 - [x] Adds and enables the [menu_admin_per_menu](https://www.drupal.org/project/menu_admin_per_menu) module
 - [x] Allows the HR user to be able to edit menu links in the Page Hierarchies menu.

## Profile requirements:

- Does deploying this change require a change to config at the site level (choose one)?
  - [ ] No config change is required.
  - [x] Yes, and I have written an update hook to apply these config changes.
  - [ ] Yes, and I've included updating instructions to be added to the release notes. The next release will need to be a major version increase. (Only do this in special cases.)

## Site-level pull requests for testing. Only merge when these PRs are approved:

Create or update any site-level pull requests following [the documentation](https://github.com/wri/WRIN/wiki/WRI-Dev-Workflow-(Thinkshout)#generating-a-multidev-for-wri_sites-work-review)

- [x] Flagship PR: https://github.com/wri/wriflagship/pull/1204

## Checked on develop (TA to do)

- [ ] Brasil
- [ ] China
- [ ] Indonesia

### CODE REVIEW

**Review by mariacha — CHANGES_REQUESTED** [review]
Nice and easy -- can you also add an update hook to the wri_admin module that enables the `menu_admin_per_menu` module? It'll make my life easier!

**Comment by komejo** [comment]
@mariacha Should I also add the change to `config/user.role.hr.yml` change here? https://github.com/wri/wriflagship/pull/1204/commits/e9f537a08483cc37fa142c648bd3a0a7b9db6f53#diff-05070aafedb1efcaba74033e874e054602d9e5a8a247625d7ae64f7c18523b70

**Comment by mariacha** [comment]
Yes! That would be very helpful!

**Review by mariacha — APPROVED** [review]

**Comment by mariacha** [comment]
Looks good now -- thanks!

**Pull request merged**
